spring.application.name=angelesyvalientes
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto:update
spring.jpa.show-sql:true

#spring.datasource.url=jdbc:mysql://www.angelesyvalientes.org:3306/angeles1_test?serverTimezone=UTC
#spring.datasource.username=angeles1
#spring.datasource.password=DIj6]P9.Tj85fo

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}